[GraduationProject, Group 7] Review code
kristina-oleinikova/FinalProjectAQA pull request #12
Opened 2023-09-22 03:18 UTC by kristina-oleinikova

Develop -> Master branch

2023-10-01 20:13 UTC, wildpioneer requested changes

2023-10-01 20:13 UTC, wildpioneer commented on pom.xml
>          <testng.version>7.7.1</testng.version>
почему папкв .idea закомичена?

2023-10-01 20:13 UTC, wildpioneer commented on src/test/java/models/Run.java
> +@Builder
@Data и @Builder в одном классе?

2023-10-01 20:13 UTC, wildpioneer commented on src/test/java/stepDefs/ExceedingTest.java
> +    public ExceedingTest(BaseTest baseTest){
Форматирование - пустые строки между методами

2023-10-01 20:13 UTC, wildpioneer commented on src/test/java/stepDefs/GetProjects.java
> +        response.then();
??? Не понимаю этого шага

2023-10-01 20:13 UTC, wildpioneer commented on src/test/java/stepDefs/GetSingleProject.java
> +        int actualCode = response.then().extract().statusCode();
Почему проверку статусКода надо было делать именно так?

2023-10-02 03:41 UTC, kristina-oleinikova commented on pom.xml
>          <testng.version>7.7.1</testng.version>
исправлено

2023-10-02 03:41 UTC, kristina-oleinikova commented on src/test/java/stepDefs/ExceedingTest.java
> +    public ExceedingTest(BaseTest baseTest){
исправлено

2023-10-02 04:03 UTC, kristina-oleinikova commented on src/test/java/stepDefs/GetProjects.java
> +        response.then();
поняла свою ошибку, исправлено

2023-10-02 04:11 UTC, kristina-oleinikova commented on src/test/java/stepDefs/GetSingleProject.java
> +        int actualCode = response.then().extract().statusCode();
поняля, что выглядит избыточно
исправила

2023-10-02 09:22 UTC, kristina-oleinikova commented on src/test/java/models/Run.java
> +@Builder
исправлено

2023-10-16 07:40 UTC, merged